import type { Metadata } from "next";

import { Inter, Jost } from "next/font/google";
import Header from "@/components/Header";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const jostFont = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-0">
        {/* <div className="flex flex-1 flex-col w-full h-full clear-both float-left relative"> */}
        <div className="flex flex-col w-full h-full">
          <Header></Header>
          {children}
        </div>
      </body>
    </html>
  );
}
